spring:
  application:
    name: center
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 9000
  servlet:
    context-path: /api

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.common.manager.repository.entity.**